

default_platform(:ios)

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
      match(app_identifier: 'com.wifiqrcode', type: 'development', readonly: true)
      match(app_identifier: 'com.wifiqrcode', type: 'appstore', readonly: true)
    end
  # desc 'Build the iOS application.'
  #   private_lane :build do
  #     certificates
  #     increment_build_number(xcodeproj: './MyApp1.xcodeproj')
  #     gym(scheme: 'MyApp1', project: './MyApp1.xcodeproj')
  #   end

  desc 'Ship to Testflight.'
    lane :beta do
      build_app(scheme: "MyApp1", workspace: "MyApp1.xcworkspace", include_bitcode: true)
      pilot
      commit_version_bump(message: 'Bump build')
      push_to_git_remote
    end
end



